# .gitpod.yml
image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip install --no-cache-dir -r requirements.txt
    command: |
      # start MinIO in the background
      minio server /data --console-address ":9001" &
      # then start Jupyter Lab
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root

ports:
  - port: 8888
    onOpen: open-preview
  - port: 9000
    onOpen: ignore
  - port: 9001
    onOpen: open-preview